name: Release package
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
      release-notes:
        description: "Release notes"
        type: string
      release-notes-path:
        description: "Release notes path"
        type: string
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  release-package:
    runs-on: ubuntu-latest
    steps:
      - name: release-package
        uses: michijs/.github/.github/actions/release-package@main
        with:
          michijs_bot_app_id: ${{ vars.MICHIJS_BOT_APP_ID }}
          michijs_bot_private_key: ${{ secrets.MICHIJS_BOT_PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release-notes-path: ${{ github.event.inputs.release-notes-path }}
          release-type: ${{ github.event.inputs.release-type }}
          release-notes: ${{ github.event.inputs.release-notes }}

